operations:

  - id: "01"
    name: "Virtual Try-On"
    workflow: "dynamic_prompting"
    template: "virtual_try.txt"
    description: "Try on clothes or apparels virtually"
  
  - id: "02"
    name: "Multi-angle Generation"
    workflow: "dynamic_prompting"
    template: "op01_multiangle.txt"
    description: "Generate multiple angles of the product for a 360-degree view"

  - id: "03"
    name: "Close-up or Macro-view generation"
    workflow: "dynamic_prompting"
    template: "op02_Closeup_macro.txt"
    description: "Generate close up view to highlight details or textures"

  - id: "04"
    name: "Lifestyle and Contextual Placement"
    workflow: "dynamic_prompting"
    template: "lifestyle_contextual.txt"
    description: "Place the product in a lifestyle setting or context"

  #- id: "05"
  #  name: "Packaging Visualization"
  #  workflow: "dynamic_prompting"
  #  template: "op04_package.txt"
  #  description: "Generate product-in-packaging and box design renders"

  - id: "06"
    name: "Material & Finish Simulation"
    workflow: "dynamic_prompting"
    template: "op08_material_finish.txt"
    description: "Simulate variations in material texture (matte, gloss, metal, fabric weave)"

  - id: "07"
    name: "Dimension and Scale Visualization"
    workflow: "dynamic_prompting"
    template: "dimension_and_feature_overlay.txt"
    description: "Add rulers, human/object scale, or dimension lines"

  - id: "08"
    name: "In-Room or Contextual Render"
    workflow: "dynamic_prompting"
    template: "op09_inroom_ver2.txt"
    description: "Generate AI-staged environments (living room, workshop, bathroom, vehicle)"

  - id: "09"
    name: "Port or Interface Highlighting"
    workflow: "dynamic_prompting"
    template: "op10_port.txt"
    description: "Generate annotated or zoomed images showing ports, buttons, displays"

  - id: "10"
    name: "Product Variant Simulation"
    workflow: "dynamic_prompting"
    template: "op12_product variant.txt"
    description: "Create color/pattern/finish variations automatically"

  - id: "11"
    name: "Ingredient or Feature Highlight Visualization"
    workflow: "dynamic_prompting"
    template: "op16_features.txt"
    description: "Highlight key ingredients or features visually"

  - id: "12"
    name: "Pure white background generation"
    workflow: "dynamic_prompting"
    template: "pure_white_bg.txt"
    description: "Creates a pure white background for product, no shadows or reflections"

  - id: "13"
    name: "Background removal"
    workflow: "dynamic_prompting"
    template: "background_removal.txt"
    description: "Remove image background"

  - id: "14"
    name: "Product isolation"
    workflow: "dynamic_prompting"
    template: "product_isolation.txt"
    description: "Isolate just the product from image"

  - id: "15"
    name: "Generate product shadow and reflection"
    workflow: "dynamic_prompting"
    template: "shadow_and_reflectionver2.txt"
    description: "Generate product shadow and reflection for realism"

  - id: "16"
    name: "Background replacement"
    workflow: "dynamic_prompting"
    template: "background_replacement.txt"
    description: "Replace plain backgrounds with user-provided ones"

  - id: "17"
    name: "Environmental Lighting Simulation"
    workflow: "dynamic_prompting"
    template: "environmental_lighting.txt"
    description: "Simulate lighting types: daylight, indoor, studio, neon"

  - id: "18"
    name: "Perspective Correction"
    workflow: "dynamic_prompting"
    template: "perspective_correction.txt"
    description: "Fix skewed or distorted views"

  - id: "19"
    name: "Annotation and Feature Overlay"
    workflow: "dynamic_prompting"
    template: "annotation_and_feature_overlayver2.txt"
    description: "Auto-tag or label product parts visually"

  - id: "20"
    name: "Infographic or Data Overlay"
    workflow: "dynamic_prompting"
    template: "Infographic or Data Overlay.txt"
    description: "Overlay specs or dimensions visually (voltage, size, weight)"
    
  - id: "21"
    name: "Seasonal_Thematic_Contexts"
    workflow: "dynamic_prompting"
    template: "Seasonal_Thematic_Contexts.txt"
    description: "Place product in a specific theme."

  - id: "22"
    name: "SKU"
    workflow: "dynamic_prompting"
    template: "sku_1.txt"
    description: "Set view"

  - id: "23"
    name: "Solid Plain Background"
    workflow: "dynamic_prompting"
    template: "solid_plain_bg.txt"
    description: "Create Solid/plain background"
    